# -*- coding: utf-8 -*-
"""Questionnarie_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14jHB4y96VW0zm7I3o-SPbmyx_IT30All
"""

# Autism Detection Model - Train / Validate / Test Pipeline
# Dataset: 40-item questionnaire + Age + Gender -> Label (0=No, 1=Yes)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    classification_report, confusion_matrix,
    roc_auc_score, roc_curve, accuracy_score, ConfusionMatrixDisplay
)

# --- Models ---
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# ─────────────────────────────────────────────
# 1. LOAD & CLEAN DATA
# ─────────────────────────────────────────────
print("=" * 60)
print("STEP 1: Loading and Cleaning Data")
print("=" * 60)

df = pd.read_csv("/content/high_accuracy_autism_dataset.csv")

# Drop any duplicate header rows (artifact of some exports)
df = df[df["Label"].isin(["0", "1", "0.5", 0, 1, 0.5])].copy()
df["Label"] = df["Label"].replace(0.5, 0)  # borderline treated as non-ASD
df["Label"] = df["Label"].astype(int)
df["Label"] = df["Label"].astype(int)
df["Age"]   = pd.to_numeric(df["Age"], errors="coerce")
df = df.dropna(subset=["Age"])
df["Age"] = df["Age"].astype(int)

# Encode Gender (M=1, F=0)
le = LabelEncoder()
df["Gender_enc"] = le.fit_transform(df["Gender"].str.strip())

print(f"Samples after cleaning : {len(df)}")
print(f"Class distribution     : {df['Label'].value_counts().to_dict()}")
print(f"Features               : Q1–Q40, Age, Gender")
print()

# ─────────────────────────────────────────────
# 2. FEATURE / TARGET SPLIT
# ─────────────────────────────────────────────
question_cols = [f"Q{i}" for i in range(1, 41)]

# --- MODIFICATION: Remove top 5 highly correlated features ---
# Based on previous correlation analysis (Q19, Q31, Q30, Q11, Q7)
features_to_remove = ["Q19", "Q31", "Q30", "Q11", "Q7"]
filtered_question_cols = [q for q in question_cols if q not in features_to_remove]

feature_cols  = filtered_question_cols + ["Age", "Gender_enc"]

X = df[feature_cols].values
y = df["Label"].values

# ─────────────────────────────────────────────
# 3. TRAIN / VALIDATION / TEST SPLIT
#    60% train | 20% validation | 20% test
# ─────────────────────────────────────────────
print("=" * 60)
print("STEP 2: Train / Validation / Test Split  (60/20/20)")
print("=" * 60)

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.40, random_state=42, stratify=y
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

print(f"  Train      : {len(X_train)} samples")
print(f"  Validation : {len(X_val)}  samples")
print(f"  Test       : {len(X_test)}  samples")
print()

# ─────────────────────────────────────────────
# 4. DEFINE MODELS (with Pipelines → auto-scaling)
# ─────────────────────────────────────────────
# --- MODIFICATION: Adjust hyperparameters for regularization/complexity ---
models = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("clf",    LogisticRegression(max_iter=1000, random_state=42, C=0.5, class_weight='balanced'))
    ]),
    "Random Forest": Pipeline([
        ("scaler", StandardScaler()),
        ("clf",    RandomForestClassifier(n_estimators=100, random_state=42, max_depth=5))
    ]),
    "Gradient Boosting": Pipeline([
        ("scaler", StandardScaler()),
        ("clf",    GradientBoostingClassifier(n_estimators=100, random_state=42, max_depth=3))
    ]),
    "SVM (RBF)": Pipeline([
        ("scaler", StandardScaler()),
        ("clf",    SVC(kernel="rbf", probability=True, random_state=42))
    ]),
    "K-Nearest Neighbours": Pipeline([
        ("scaler", StandardScaler()),
        ("clf",    KNeighborsClassifier(n_neighbors=10)) # Increased n_neighbors
    ]),
}

# ─────────────────────────────────────────────
# 5. CROSS-VALIDATION ON TRAINING SET (5-fold)
# ─────────────────────────────────────────────
print("=" * 60)
print("STEP 3: 5-Fold Cross-Validation on Training Set")
print("=" * 60)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_results = {}

for name, model in models.items():
    scores = cross_val_score(model, X_train, y_train,
                             cv=cv, scoring="roc_auc")
    cv_results[name] = scores
    print(f"  {name:<25}  AUC = {scores.mean():.4f} ± {scores.std():.4f}")

print()

# ─────────────────────────────────────────────
# 6. TRAIN ON FULL TRAIN SET, EVALUATE ON VALIDATION
# ─────────────────────────────────────────────
print("=" * 60)
print("STEP 4: Validation Set Performance")
print("=" * 60)

val_results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred      = model.predict(X_val)
    y_prob      = model.predict_proba(X_val)[:, 1]
    acc         = accuracy_score(y_val, y_pred)
    auc         = roc_auc_score(y_val, y_prob)
    val_results[name] = {"acc": acc, "auc": auc,
                         "y_pred": y_pred, "y_prob": y_prob}
    print(f"  {name:<25}  Acc = {acc:.4f}  |  AUC = {auc:.4f}")

print()

# Pick best model by validation AUC
best_name = max(val_results, key=lambda n: val_results[n]["auc"])
best_model = models[best_name]
print(f"  ✅ Best model (val AUC): {best_name}")
print()

# ─────────────────────────────────────────────
# 7. FINAL TEST SET EVALUATION (best model only)
# ─────────────────────────────────────────────
print("=" * 60)
print(f"STEP 5: Test Set Evaluation  ->  {best_name}")
print("=" * 60)

# Retrain on train+val combined, then test
X_train_full = np.vstack([X_train, X_val])
y_train_full = np.concatenate([y_train, y_val])
best_model.fit(X_train_full, y_train_full)

y_test_pred = best_model.predict(X_test)
y_test_prob = best_model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_test_pred,
                             target_names=["No Autism (0)", "Autism (1)"]))
print(f"  Test AUC : {roc_auc_score(y_test, y_test_prob):.4f}")
print()

# ─────────────────────────────────────────────
# 8. PLOTS
# ─────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("Autism Detection Model - Evaluation Dashboard", fontsize=14, fontweight="bold")

# --- 8a. Cross-validation AUC comparison ---
ax = axes[0]
names  = list(cv_results.keys())
means  = [cv_results[n].mean() for n in names]
stds   = [cv_results[n].std()  for n in names]
colors = ["steelblue" if n != best_name else "darkorange" for n in names]
bars   = ax.barh(names, means, xerr=stds, color=colors,
                 align="center", capsize=4, edgecolor="black", linewidth=0.6)
ax.set_xlabel("Mean AUC (5-fold CV)")
ax.set_title("Cross-Validation AUC Comparison")
ax.set_xlim(0, 1.05)
for bar, mean in zip(bars, means):
    ax.text(mean + 0.01, bar.get_y() + bar.get_height() / 2,
            f"{mean:.3f}", va="center", fontsize=9)
ax.invert_yaxis()

# --- 8b. Confusion matrix (test set) ---
ax = axes[1]
cm = confusion_matrix(y_test, y_test_pred)
disp = ConfusionMatrixDisplay(cm, display_labels=["No Autism", "Autism"])
disp.plot(ax=ax, cmap="Blues", colorbar=False)
ax.set_title(f"Confusion Matrix - {best_name}\n(Test Set)")

# --- 8c. ROC curve (test set) ---
ax = axes[2]
fpr, tpr, _ = roc_curve(y_test, y_test_prob)
auc_score   = roc_auc_score(y_test, y_test_prob)
ax.plot(fpr, tpr, color="darkorange", lw=2,
        label=f"ROC (AUC = {auc_score:.3f})")
ax.plot([0, 1], [0, 1], "k--", lw=1)
ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_title(f"ROC Curve - {best_name}")
ax.legend(loc="lower right")
ax.set_xlim([0, 1])
ax.set_ylim([0, 1.02])

plt.tight_layout()
plt.savefig("autism_model_results.png", dpi=150, bbox_inches="tight")
print("  📊 Plot saved -> autism_model_results.png")

# ─────────────────────────────────────────────
# 9. FEATURE IMPORTANCE (if tree-based)
# ─────────────────────────────────────────────
clf = best_model.named_steps["clf"]
# --- MODIFICATION: Update feature_cols for feature importance plot ---
if hasattr(clf, "feature_importances_") and best_name in ["Random Forest", "Gradient Boosting"]:
    importances = clf.feature_importances_
    feat_df = pd.DataFrame({
        "Feature":    feature_cols, # Use updated feature_cols
        "Importance": importances
    }).sort_values("Importance", ascending=False)

    print()
    print("=" * 60)
    print("STEP 6: Top-10 Feature Importances")
    print("=" * 60)
    print(feat_df.head(10).to_string(index=False))

    fig2, ax2 = plt.subplots(figsize=(10, 5))
    top = feat_df.head(15)
    ax2.barh(top["Feature"][::-1], top["Importance"][::-1],
             color="steelblue", edgecolor="black", linewidth=0.5)
    ax2.set_xlabel("Feature Importance")
    ax2.set_title(f"Top-15 Feature Importances - {best_name}")
    plt.tight_layout()
    plt.savefig("autism_feature_importance.png", dpi=150, bbox_inches="tight")
    print("\n  📊 Feature importance plot saved -> autism_feature_importance.png")
else:
    print("\n  💡 Feature importance not available for selected model or not tree-based.")

print()
print("=" * 60)
print("DONE. Model training & evaluation complete.")
print("=" * 60)

"""### Investigating 100% Accuracy

To diagnose the 100% accuracy, let's look for strong correlations between individual features and the target variable. An extremely high correlation (close to 1 or -1) for any single feature might suggest data leakage or that the problem is trivially easy. If such a feature is present, the model might simply be learning a direct mapping rather than a complex pattern.
"""

# Recalculate the DataFrame to include all necessary columns for correlation
df_full = pd.read_csv("/content/high_accuracy_autism_dataset.csv")
# Perform the same cleaning and encoding steps as in the original notebook
df_full = df_full[df_full["Label"].isin(["0", "1", 0, 1])].copy()
df_full["Label"] = df_full["Label"].astype(int)
df_full["Age"] = pd.to_numeric(df_full["Age"], errors="coerce")
df_full = df_full.dropna(subset=["Age"])
df_full["Age"] = df_full["Age"].astype(int)
le = LabelEncoder()
df_full["Gender_enc"] = le.fit_transform(df_full["Gender"].str.strip())

# Define feature columns and target as in the original notebook
question_cols = [f"Q{i}" for i in range(1, 41)]
feature_cols = question_cols + ["Age", "Gender_enc"]

# Combine features and target for correlation calculation
df_correlation = df_full[feature_cols + ["Label"]]

# Calculate correlation matrix
correlation_matrix = df_correlation.corr()

# Display correlations with the target 'Label'
print("Correlation of features with the target 'Label':")
display(correlation_matrix['Label'].sort_values(ascending=False))

# You can also visualize this with a heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=False, cmap='coolwarm', fmt=".2f")
plt.title('Feature Correlation Matrix')
plt.show()

"""After reviewing the correlation, especially look for any feature that has a correlation value very close to `1.0` or `-1.0` with the `Label` column. This could indicate that the feature is almost a direct copy or a perfect predictor of the target, leading to data leakage.

Also, consider manually inspecting the raw data in the `realistic_autism_dataset.csv` file, paying close attention to the `Label` column and its relationship with other columns. Sometimes, accidental encoding or inclusion of a diagnosis-related column can cause this behavior.

If the correlations seem reasonable (i.e., no single feature perfectly correlates with the target), the next step would be to review the `X` and `y` variables directly before splitting to ensure no issues there.
"""

# ─────────────────────────────────────────────────────────────────
# CELL 1 — Install & Import
# ─────────────────────────────────────────────────────────────────
# !pip install scikit-learn pandas numpy --quiet   # ← Uncomment in Colab

import pandas as pd
import numpy as np
import warnings
import os
import pickle
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier   # ✅ ADD THIS

from sklearn.linear_model import LogisticRegression   # (if you use it)

from sklearn.metrics import classification_report, accuracy_score
print("✅ Libraries loaded successfully.")

# ─────────────────────────────────────────────────────────────────
# CELL 2 — Train & Save Model  (skip if model already saved)
# ─────────────────────────────────────────────────────────────────

MODEL_PATH = "autism_model.pkl"

def train_and_save_model(csv_path="questionnarie.csv"):
    """Trains the model on the dataset and saves it to disk."""
    print("🔄 Training model on dataset...")

    df = pd.read_csv(csv_path)

    df = df[df["Label"].isin(["0", "1", 0, 1])].copy()
    df["Label"]  = df["Label"].astype(int)
    df["Age"]    = pd.to_numeric(df["Age"], errors="coerce")
    df = df.dropna(subset=["Age"])
    df["Gender_enc"] = df["Gender"].str.strip().map({"M": 1, "F": 0}).fillna(0).astype(int)

    question_cols = [f"Q{i}" for i in range(1, 41)]
    feature_cols  = question_cols + ["Age", "Gender_enc"]

    X = df[feature_cols].values
    y = df["Label"].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )


    model = Pipeline([
        ("scaler", StandardScaler()),
        ("clf", RandomForestClassifier(
            n_estimators=100,
            max_depth=5,
            random_state=42
        ))
    ])
    scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")

    print(f"📊 Cross-validation Accuracy: {scores.mean()*100:.2f}% ± {scores.std()*100:.2f}%")

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    acc    = accuracy_score(y_test, y_pred)
    print(f"✅ Model trained!  Test Accuracy: {acc*100:.1f}%")

    with open(MODEL_PATH, "wb") as f:
        pickle.dump(model, f)
    print(f"💾 Model saved to '{MODEL_PATH}'")
    return model


def load_model():
    """Load saved model from disk."""
    with open(MODEL_PATH, "rb") as f:
        model = pickle.load(f)
    print(f"✅ Model loaded from '{MODEL_PATH}'")
    return model


# Auto-train if model not found
if os.path.exists(MODEL_PATH):
    model = load_model()
elif os.path.exists("/content/high_accuracy_autism_dataset.csv"):
    model = train_and_save_model("/content/high_accuracy_autism_dataset.csv")
else:
    print("⚠️  No model or dataset found.")
    print("   Please upload 'questionnarie.csv' or 'autism_model.pkl' and re-run.")
    model = None


# ─────────────────────────────────────────────────────────────────
# CELL 3 — Question Bank
# ─────────────────────────────────────────────────────────────────

SECTIONS = {
    "🤝 Social Interaction": [
        "Does your child respond to their name?",
        "Does your child make eye contact?",
        "Does your child smile back when smiled at?",
        "Does your child show interest in other children?",
        "Does your child try to share enjoyment with you?",
        "Does your child point to show interest?",
        "Does your child wave goodbye?",
        "Does your child imitate actions?",
        "Does your child follow your gaze?",
        "Does your child bring objects to show you?",
    ],
    "💬 Communication": [
        "Does your child use gestures to communicate?",
        "Does your child understand simple instructions?",
        "Does your child babble or speak words?",
        "Does your child respond when spoken to?",
        "Does your child use meaningful sounds?",
        "Does your child ask for help when needed?",
        "Does your child respond to emotions?",
        "Does your child engage in back-and-forth sounds?",
        "Does your child use facial expressions?",
        "Does your child try to start conversations?",
    ],
    "🔁 Behavior Patterns": [
        "Does your child repeat actions again and again?",
        "Does your child show unusual attachment to objects?",
        "Does your child line up toys?",
        "Does your child get upset with small changes?",
        "Does your child show repetitive movements (e.g. hand flapping)?",
        "Does your child focus on parts of objects?",
        "Does your child spin or rock frequently?",
        "Does your child insist on routines?",
        "Does your child play with toys in unusual ways?",
        "Does your child show intense interest in specific things?",
    ],
    "🎯 Sensory & Emotional": [
        "Does your child react strongly to loud sounds?",
        "Does your child avoid eye contact?",
        "Does your child show limited emotional expression?",
        "Does your child overreact to touch?",
        "Does your child ignore pain or temperature?",
        "Does your child get easily frustrated?",
        "Does your child have difficulty calming down?",
        "Does your child show fear without reason?",
        "Does your child avoid social interaction?",
        "Does your child prefer to play alone?",
    ],
}

SCALE_LABEL = "  [0 = Never  |  1 = Rarely  |  2 = Sometimes  |  3 = Often  |  4 = Always]"

# ─────────────────────────────────────────────────────────────────
# CELL 4 — Interactive Questionnaire
# ─────────────────────────────────────────────────────────────────

def get_valid_int(prompt, lo=0, hi=4):
    """Keep asking until user enters a valid integer in [lo, hi]."""
    while True:
        raw = input(prompt).strip()
        if raw.isdigit() and lo <= int(raw) <= hi:
            return int(raw)
        print(f"   ⚠️  Please enter a number between {lo} and {hi}.")


def get_valid_gender():
    while True:
        g = input("   Enter Gender (M / F): ").strip().upper()
        if g in ("M", "F"):
            return 1 if g == "M" else 0
        print(f"   ⚠️  Please enter M or F.")


def run_questionnaire():
    print("\n" + "═" * 65)
    print("   🧠  AUTISM EARLY SCREENING QUESTIONNAIRE")
    print("═" * 65)
    print("  Answer each question honestly based on your child's")
    print("  typical behaviour over the past 3–6 months.")
    print("  ⚠️  DISCLAIMER: This is a screening tool only.")
    print("  It does NOT replace a professional clinical diagnosis.")
    print("═" * 65)

    # ── Basic info ──────────────────────────────────────────────
    print("\n📋  SECTION: Child Information")
    print()
    age        = get_valid_int("   Child's Age (in years, 1–6): ", lo=1, hi=6)
    gender_enc = get_valid_gender()

    # ── 40 questions across 4 sections ─────────────────────────
    responses = []
    q_number  = 1

    for section_title, questions in SECTIONS.items():
        print(f"\n{'─'*65}")
        print(f"  {section_title}")
        print(f"{'─'*65}")
        print(SCALE_LABEL)
        print()

        for question in questions:
            answer = get_valid_int(f"  Q{q_number:02d}. {question}\n       → ", lo=0, hi=4)
            responses.append(answer)
            q_number += 1

    return responses, age, gender_enc


# ─────────────────────────────────────────────────────────────────
# CELL 5 — Predict & Display Result
# ─────────────────────────────────────────────────────────────────

def display_result(probability, responses, age):
    """Print a rich, user-friendly result summary."""
    percent    = probability * 100
    prediction = "Autism Indicators Detected" if probability >= 0.5 else "No Significant Autism Indicators"

    # Section scores (average per section, scaled to %)
    section_names  = list(SECTIONS.keys())
    section_scores = []
    for i, name in enumerate(section_names):
        chunk = responses[i*10 : (i+1)*10]
        avg   = sum(chunk) / (len(chunk) * 4) * 100   # % of max possible
        section_scores.append((name, avg))

    print("\n" + "═"*65)
    print("   📊  SCREENING RESULT SUMMARY")
    print("═"*65)

    if probability < 0.3:
        flag = "🟢"
        risk = "LOW"
    elif probability < 0.6:
        flag = "🟡"
        risk = "MODERATE"
    elif probability < 0.8:
        flag = "🟠"
        risk = "ELEVATED"
    else:
        flag = "🔴"
        risk = "HIGH"

    print(f"\n  {flag}  Risk Level      : {risk}")
    print(f"  📈  Autism Probability : {percent:.1f}%")
    print(f"  🔍  Assessment         : {prediction}")
    print(f"\n{'─'*65}")
    print("  📂  SECTION BREAKDOWN  (% of maximum possible score)")
    print(f"{'─'*65}")

    for name, score in section_scores:
        filled  = int(score / 5)
        bar     = "█" * filled + "░" * (20 - filled)
        print(f"  {name}")
        print(f"     [{bar}]  {score:.1f}%")
        print()

    print("─"*65)
   11


def run_screening(model):
    """Full pipeline: questionnaire → prediction → re4sult."""
    if model is None:
        print("❌ No model available. Please train the model first (Cell 2).")
        return

    try:
        responses, age, gender_enc = run_questionnaire()
    except KeyboardInterrupt:
        print("\n\n⚠️  Questionnaire cancelled by user.")
        return
    # ── FIX: Invert positive-behaviour questions ───────────────
    INVERT_QUESTIONS = list(range(1, 21))  # Q1–Q20 (Social + Communication)

    responses = [
        4 - r if (i + 1) in INVERT_QUESTIONS else r
        for i, r in enumerate(responses)
    ]
    # Build feature vector (Q1–Q40, Age, Gender_enc)
    # ── Section-wise scoring ─────────────────────────────
    social        = sum(responses[0:10])  / 40
    communication = sum(responses[10:20]) / 40
    behavior      = sum(responses[20:30]) / 40
    sensory       = sum(responses[30:40]) / 40

    # ── Weighted score (MAIN FIX) ───────────────────────
    weighted_score = (
        0.25 * social +
        0.25 * communication +
        0.30 * behavior +
        0.20 * sensory
    )

    # Optional: combine with model (hybrid)
    features = np.array(responses + [age, gender_enc]).reshape(1, -1)
    model_prob = model.predict_proba(features)[0][1]

    # Final probability (balanced)
    probability = (0.6 * model_prob) + (0.4 * weighted_score)
    display_result(probability, responses, age)

    # ── Ask to save ────────────────────────────────────────────
    save = input("  💾  Save this result to a file? (y/n): ").strip().lower()
    if save == "y":
        result_df = pd.DataFrame(
            [responses + [age, "M" if gender_enc == 1 else "F",
                          round(probability, 4),
                          "Low" if probability < 0.3 else
                          "Moderate" if probability < 0.6 else
                          "Elevated" if probability < 0.8 else
                          "High"]],
            columns=[f"Q{i}" for i in range(1, 41)] + ["Age", "Gender", "Probability", "Risk"]
        )
        fname = "screening_result.csv"
        result_df.to_csv(fname, index=False)
        print(f"\n  ✅  Result saved to '{fname}'")


# ─────────────────────────────────────────────────────────────────
# CELL 6 — RUN  (execute this cell to start the questionnaire)
# ─────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    run_screening(model)